# Generated by Django 5.2.5 on 2025-08-09 12:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='searchhistory',
            old_name='searched_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='viewhistory',
            old_name='viewed_at',
            new_name='created_at',
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['created_at'], name='analytics_s_created_88ec14_idx'),
        ),
        migrations.AddIndex(
            model_name='searchhistory',
            index=models.Index(fields=['search_query'], name='analytics_s_search__f871c7_idx'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['created_at'], name='analytics_v_created_1dc85c_idx'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['property'], name='analytics_v_propert_500b10_idx'),
        ),
        migrations.AddIndex(
            model_name='viewhistory',
            index=models.Index(fields=['user', 'property'], name='analytics_v_user_id_1178f1_idx'),
        ),
    ]
