# Generated by Django 5.2.5 on 2025-08-08 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers_remove_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('renter', 'Арендатор'), ('landlord', 'Арендодатель')], default='renter', max_length=20),
        ),
    ]
