# Generated by Django 5.2.5 on 2025-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='property',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Квартира'), ('house', 'Дом'), ('room', 'Комната'), ('other', 'Другое')], max_length=20),
        ),
    ]
