# Generated by Django 5.2.5 on 2025-08-11 11:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_confirmed_at_booking_monthly_rent_and_more'),
        ('properties', '0003_property_main_image_propertyimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', 'end_date'], name='bookings_bo_status_58e56c_idx'),
        ),
    ]
