# Generated by Django 5.2.5 on 2025-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('booking_new', 'Новая заявка на бронирование (для арендодателя)'), ('booking_confirmed', 'Подтверждение бронирования (для арендатора)'), ('booking_rejected', 'Отклонение бронирования (для арендатора)'), ('review_new', 'Новый отзыв')], max_length=50),
        ),
    ]
